name: Dependabot Auto Merge
on:
  pull_request_target:
    types: [labeled, edited]

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm v9.x
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install deps
        run: pnpm i

      - name: Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: merge
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
